<?php
$menuStore = Velacolib\Utility\Utility::getMenuStore() ;

?>
<div class='controls'>
    <div class='caret'></div>
    <div class='form-wrapper'>
        <h1 class='text-center'>Report Total Quantity of Product</h1>
        <form accept-charset="UTF-8" action="<?php echo $this->url('admin/child',array('controller'=>'report','action'=>'menu')); ?>" method="post" /><div style="margin:0;padding:0;display:inline"></div>
        <div class='row-fluid'>
            <div class='span12 icon-over-input'>
             <select name="menu" class="span5" onchange="this.form.submit()">
                 <option value="0">Select Menu</option>
                 <?php
                 foreach($menuStore as $menu):   ?>
                     <option value="<?=$menu->getId()?>"><?=$menu->getName();?></option>
               <?php
                 endforeach;
                 ?>
             </select>
            </div>
        </div>
              <button class="btn btn-danger"  type="submit">Find</button>
        </form>
        <div class='text-center'>
            <hr class='hr-normal' />

        </div>
    </div>
</div>
<?php if(isset($menuItem)): ?>
<div class="row-fluid">
    <h3>Find by : <?php $menustoreInfo = Velacolib\Utility\Utility::getMenuStoreInfo($menuId); echo $menustoreInfo->getName() ?></h3>
    <table class="table">
        <thead>
            <th>Name</th>
            <th>Quantity</th>
            <th>Unit</th>
            <th>Order</th>
            <th>Sum</th>

        </thead>
        <tbody>

        <?php
        $totals  = 0;
        foreach($menuItem as $item): ?>
        <tr>
            <td>
                <?php $menuInfo =  Velacolib\Utility\Utility::getMenuInfo($item->getMenuId()); ?>
                <?php echo $menuInfo->getName() ?>
            </td>
            <td><?php echo $item->getQuantity();  ?></td>
            <td><?php echo $item->getUnit();  ?></td>
            <td><?php $orderDetail = Velacolib\Utility\Utility::countOrderDetail($item->getMenuId());
                $sum =  $orderDetail[0][1];
                echo $sum;
                ?>
            </td>
            <td>
                <?php
                $total =  $sum * $item->getQuantity();
                echo $total;
                $totals += $total;
                ?>
            </td>

        </tr>
        <?php endforeach; ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4">Summary</td>
            <td ><?php echo $totals; ?></td>
        </tr>
        </tfoot>
    </table>
</div>
<?php endif ?>
