<?php
$translator = \Velacolib\Utility\Utility::translate();
$config = Velacolib\Utility\Utility::getConfig();

?>
<header>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid">
<!--                <a style="padding: 0px; margin-right:0px " class="brand" href="/">-->
<!--                  <img src="--><?php //echo $this->basePath().$config['logo']; ?><!--">-->
<!--                </a>-->
<!--                <a class="toggle-nav btn pull-left" style="margin-left: 10px" href="#">-->
<!--                    <i class="icon-reorder"></i>-->
<!--                </a>-->
                <div class="span3">
                    <img src="<?php echo $this->basePath().$config['logo']; ?>" />
                </div>

                <ul style="margin-left: 5px" class="nav pull-right">

                    <?php
                    $user = \Velacolib\Utility\Utility::checkLogin();
                    if($user){
//
                        ?>
                        <li class="dropdown dark user-menu ">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <?php if(isset($user->image)){ ?>
                                    <img alt="<?php echo $user->userName; ?>" height="23" src="/assets/images/avatar.jpg" width="23">
                                <?php } ?>

                                <span class="user-name hidden-phone"><?php echo $user->userName ?></span>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">

                            <li>
                                <a href="/admin/login/logout">
                                    <i class="icon-signout"></i>
                                    <?php echo $translator->translate('Sign out') ?>
                                </a>
                            </li>
                            </ul>

                    </li>
                    <?php } ?>
                </ul>
                <a class=" btn btn-success pull-right" href="/frontend/order/add">
                    <i class="icon-Plus"></i> <?php echo $translator->translate('Add new order') ?>
                </a>

<!--                <form accept-charset="UTF-8" action="search_results.html" class="navbar-search pull-right hidden-phone" method="get">-->
<!--                    <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="✓"></div>-->
<!--                    <button class="btn btn-link icon-search" name="button" type="submit"></button>-->
<!---->
<!--                </form>-->
            </div>
        </div>
    </div>
</header>
<div id='wrapper'>
    <div id='main-nav-bg'></div>
    <nav class='' id='main-nav'>
        <div class='navigation'>
            <div class='search'>
                <form accept-charset="UTF-8" action="search_results.html" method="get"/>
                <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;"/></div>
                <div class='search-wrapper'>
                    <input autocomplete="off" class="search-query" id="q" name="q" placeholder="Search..." type="text" value=""/>
                    <button class="btn btn-link icon-search" name="button" type="submit"></button>
                </div>
                </form>
            </div>