<?php $translator = \Velacolib\Utility\Utility::translate(); ?>
<ul class='nav nav-stacked'>
    <li class=''>
        <a class='dropdown-collapse' href='/admin'>
            <i class='icon-edit'></i>
            <span><?php echo $translator->translate('Menu') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
            <li class=''>
                <a href='/admin'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('All menu') ?></span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/index/add'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Add new menu') ?></span>
                </a>
            </li>

            <li class=''>
                <a href='/admin/category'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Category') ?> </span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/category/add'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Add new category') ?> </span>
                </a>
            </li>
        </ul>
    </li>


    <li>
        <a class='dropdown-collapse ' href='/admin/table'>
            <i class='icon-tint'></i>
            <span><?php echo $translator->translate('Tables') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
            <li class=''>
                <a href='/admin/table'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Tables') ?></span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/table/add'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Add new table') ?></span>
                </a>
            </li>
        </ul>
    </li>


    <!--<li class=''>-->
    <!--    <a href='buttons_and_icons.html'>-->
    <!--        <i class='icon-star'></i>-->
    <!--        <span>Buttons & Icons</span>-->
    <!--    </a>-->
    <!--</li>-->


    <li>
        <a class='dropdown-collapse ' href='/admin/config'>
            <i class='icon-edit'></i>
            <span><?php echo $translator->translate('Orders') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
            <li class=''>
                <a href='/admin/order'>
                    <i class='icon-bar-chart'></i>
                    <span><?php echo $translator->translate('Order') ?></span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/order/add'>
                    <i class='icon-bar-chart'></i>
                    <span><?php echo $translator->translate('New order') ?></span>
                </a>
            </li>
        </ul>
    </li>
    <li>
        <a class='dropdown-collapse ' href='/admin/users'>
            <i class='icon-cogs'></i>
            <span><?php echo $translator->translate('User') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
            <li class=''>
                <a href='/admin/users'>
                    <i class='icon-bar-chart'></i>
                    <span><?php echo $translator->translate('User') ?></span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/users/add'>
                    <i class='icon-bar-chart'></i>
                    <span><?php echo $translator->translate('Add new user') ?></span>
                </a>
            </li>
        </ul>
    </li>
    <li>
        <a class='dropdown-collapse ' href='/admin/coupon'>
            <i class='icon-tint'></i>
            <span><?php echo $translator->translate('Coupon') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
        <ul class='nav nav-stacked'>
            <li class=''>
                <a href='/admin/coupon'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('All coupon') ?></span>
                </a>
            </li>
            <li class=''>
                <a href='/admin/coupon/add'>
                    <i class='icon-caret-right'></i>
                    <span><?php echo $translator->translate('Add new coupon') ?></span>
                </a>
            </li>
        </ul>
    </li>
    <!-- customer -->


    <li>
        <a class=' ' href='/admin/report'>
            <i class='icon-tint'></i>
            <span><?php echo $translator->translate('Report') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
    </li>
    <li>
        <a class=' ' href='/admin/config'>
            <i class='icon-tint'></i>
            <span><?php echo $translator->translate('Config') ?></span>
            <i class='icon-angle-down angle-down'></i>
        </a>
    </li>

</ul>
